"""Data models for extraction strategies.

This module defines Pydantic models for representing extraction strategies
generated by PM Mode analysis.
"""

from typing import Any

from pydantic import BaseModel, Field


class ExtractionPattern(BaseModel):
    """Extraction pattern for a single field.

    Attributes:
        source_path: JSON path, XPath, or regex pattern
        description: What this field represents
        optional: Whether field is optional
        default_value: Default value if missing
    """

    source_path: str = Field(..., description="Extraction path ($.path, XPath, regex)")
    description: str = Field(..., description="Field description")
    optional: bool = Field(default=False, description="Is field optional")
    default_value: Any = Field(default=None, description="Default value if missing")


class Transformation(BaseModel):
    """Data transformation specification.

    Attributes:
        field: Target field name
        operation: Transformation type
        formula: Transformation formula or code
        description: Why transformation is needed
    """

    field: str = Field(..., description="Target field name")
    operation: str = Field(
        ...,
        description="type_conversion|calculation|string_manipulation|unit_conversion",
    )
    formula: str = Field(..., description="Transformation formula")
    description: str = Field(..., description="Transformation rationale")


class ValidationRule(BaseModel):
    """Validation rule for a field.

    Attributes:
        type: Data type (int, float, string, datetime, etc.)
        constraints: Validation constraints
        error_handling: How to handle validation errors
        default_value: Default value on validation failure
    """

    type: str = Field(..., description="Data type")
    constraints: dict[str, Any] = Field(
        default_factory=dict,
        description="Validation constraints",
    )
    error_handling: str = Field(
        default="fail",
        description="fail|use_default|skip_record",
    )
    default_value: Any = Field(default=None, description="Default on failure")


class CrossFieldValidation(BaseModel):
    """Cross-field validation rule.

    Attributes:
        rule: Validation rule description
        fields: List of involved fields
        validation_logic: Detailed validation logic
    """

    rule: str = Field(..., description="Validation rule description")
    fields: list[str] = Field(..., description="Involved fields")
    validation_logic: str = Field(..., description="Validation logic")


class ErrorHandlingStrategy(BaseModel):
    """Error handling strategy.

    Attributes:
        missing_fields: How to handle missing fields
        invalid_types: How to handle type errors
        validation_failures: How to handle validation failures
    """

    missing_fields: str = Field(
        default="fail",
        description="fail|use_defaults|skip_record",
    )
    invalid_types: str = Field(
        default="fail",
        description="fail|coerce|skip_field",
    )
    validation_failures: str = Field(
        default="fail",
        description="fail|log_and_continue|skip_record",
    )


class ExtractionStrategy(BaseModel):
    """Complete extraction strategy from PM Mode.

    This model represents the structured output from PM Mode analysis,
    containing all information needed for Coder Mode to generate code.

    Attributes:
        data_source_type: Type of data source
        response_format: Response format (JSON, XML, etc.)
        extraction_patterns: Field extraction patterns
        transformations: Data transformations
        validation_rules: Field validation rules
        cross_field_validations: Cross-field validation rules
        error_handling: Error handling strategy
        assumptions: List of assumptions made
    """

    data_source_type: str = Field(
        ...,
        description="REST_API|GraphQL|RSS|WebSocket|etc",
    )
    response_format: str = Field(..., description="JSON|XML|CSV|etc")
    extraction_patterns: dict[str, ExtractionPattern] = Field(
        ...,
        description="Field extraction patterns",
    )
    transformations: list[Transformation] = Field(
        default_factory=list,
        description="Data transformations",
    )
    validation_rules: dict[str, ValidationRule] = Field(
        default_factory=dict,
        description="Field validation rules",
    )
    cross_field_validations: list[CrossFieldValidation] = Field(
        default_factory=list,
        description="Cross-field validations",
    )
    error_handling: ErrorHandlingStrategy = Field(
        default_factory=ErrorHandlingStrategy,
        description="Error handling strategy",
    )
    assumptions: list[str] = Field(
        default_factory=list,
        description="Assumptions made during analysis",
    )
